export const phrases = [
  "A las vueltas como colchón meado",
  "A las vueltas como mojarrita en palangana",
  "A los tirones como ladrón de alambre",
  "A los tirones como negra peinando el hijo",
  "Aburrido como choque de tortugas",
  "Aburrido como partida de ajedrez por radio",
  "Agrandado como sorete en kerosene",
  "Al pedo como cenicero de moto",
  "Ancho como nariz de vaca",
  "Apretado como pedo de vieja",
  "Apretado como pedo de visita",
  "Apretado como tuerca de submarino",
  "Apurado como rengo en tiroteo",
  "Áspero como caricia de albañil",
  "Áspero como sobaco de tortuga",
  "Áspero como talón de indio",
  "Asqueroso como cucharada de moco",
  "Azul como carne de paloma",
  "Blanco como tobillo de albañil",
  "Chivando como rengo en tiroteo",
  "Colorado como bragueta ladrillera",
  "Cortito como manga de chaleco",
  "Cortito como muleta de cocodrilo",
  "Cortito como parpadeo de rata",
  "Cortito como patada de chancho",
  "Cortito como patada de mosca",
  "Corto como polvo de quinceañero",
  "De un lado para el otro como huevo de rengo",
  "Delicado como eructo de suegra",
  "Desubicado como aceituna en pan dulce",
  "Desubicado como chupete en el culo",
  "Doloroso como patada ninja en los huevos",
  "Duro como caramelo de cemento",
  "Duro como cogote de estatua",
  "Duro como empanada de mármol",
  "Duro como ensalada de cascote",
  "Duro como rulo de estatua",
  "Duro como sanguche de ladrillo",
  "Duro como turrón de oferta",
  "Enano como esquimal de freezer",
  "Enano como Tarzán de maceta",
  "Estás más fuerte que dolor de ovarios",
  "Falso como beso de suegra",
  "Finito como pedo de vívora",
  "Fino como canapé de mondongo",
  "Fino como ceja turra",
  "Fino como frenada de bicicleta",
  "Fino como ojota de gordo",
  "Fino como sushi de mortadela",
  "Firme como corbata de yeso",
  "Firme como ojo de vidrio",
  "Frío como culo de pingüino",
  "Fuerte como cachetada de transformer",
  "Fuerte como eructo de Drácula",
  "Fuerte como mermelada de ajo",
  "Fuerte como patada de allanamiento",
  "Fuerte como pedo de locro",
  "Fuerte como trompada de rugbier",
  "Justito como cuatro dedos en el culo",
  "Largo como domingo sin plata",
  "Largo como eructo de jirafa",
  "Largo como piropo de tartamudo",
  "Largo como puteada de tartamudo",
  "Le entro como agua al Titanic",
  "Le entro como argentino al mate",
  "Le entro como coca al fernet",
  "Le entro como evangelista al timbre",
  "Le entro como limón a la empanada",
  "Le entro como pan al tuco", 
  "Le entro como piquetero al bombo",
  "Le entro como pobre al guiso",
  "Le entro como sordo al timbre",
  "Lento como patada de tortuga",
  "Manso como loro a pie",
  "Más agachadas que chino con visitas",
  "Más agachadas que tero",
  "Más agarrado que ciego en moto",
  "Más al pedo que bocina de avión",
  "Más al pedo que guardabarro de lancha",
  "Más al pedo que pelado con peine",
  "Más al pedo que teta de monja",
  "Más arrugado que frenada de gusano",
  "Más bueno que comer pollo con la mano",
  "Más caído que teta de gitana",
  "Más caliente que negro en baile",
  "Más cerrado que culo de muñeca",
  "Más colorado que huevo de ciclista",
  "Más cortito que viraje de laucha",
  "Más despistado que piojo en cabeza de muñeca",
  "Más difícil que remar en dulce de leche",
  "Más dudas que daltónico con cubo Rubik",
  "Más duro que alfajor de escombro",
  "Más duro que árbol de GTA",
  "Más duro que cachetada de transformer",
  "Mas duro que chipa en la heladera",
  "Más duro que el Chano",
  "Más duro que el Pity Álvarez",
  "Más duro que empanada de mármol",
  "Más duro que infancia en Siria",
  "Más duro que Maradona",
  "Más duro que sándwich de hormigón",
  "Más duro que sanguche de tortuga",
  "Más duro que talón de indio",
  "Más duro que talón de oso",
  "Más duro que zapato arriba del techo",
  "Más exagerado que regalo de padres separados",
  "Más fuerte que abrazo de huérfano",
  "Más fuerte que aliento de linyera",
  "Más fuerte que aliento de perro",
  "Más fuerte que cachetada de traba",
  "Más fuerte que cadenazo de esclavo",
  "Más fuerte que eructo de choripán",
  "Más fuerte que gárgaras de lavandina",
  "Mas fuerte que guiso de Menthoplus",
  "Más fuerte que mordida de epiléptico",
  "Más fuerte que televisor de geriátrico",
  "Más hambre que el Chavo del 8",
  "Más hambre que piojo de peluca",
  "Más hambre que vaca atada al asfalto",
  "Más humo que telegrama de indio",
  "Más largo que bife de vívora",
  "Más largo que despedida de mamado",
  "Más largo que esperanza de pobre",
  "Más largo que garage de tren",
  "Más largo que milanesa de serpiente",
  "Más lento que patada de astronauta",
  "Más metido que calzón de gorda",
  "Mas nervioso que Frodo en joyería",
  "Más nervioso que testigo falso",
  "Más noche que camión de la basura",
  "Más peligroso que MacGyver en la ferretería",
  "Más peligroso que mono con navaja",
  "Mas perdido que sordo en bingo",
  "Más rápido que escupida de músico",
  "Más rápido que Michetti en bajada",
  "Más roto que talón de cartero",
  "Más seco que empanada de talco",
  "Más seco que escupida de momia",
  "Más seco que gárgara de polenta",
  "Más seco que pañal de muñeca",
  "Más solo que Papá Noel en agosto",
  "Más tirado que pucho en la vereda",
  "Más tóxico que grafito de Chernobyl",
  "Más viejo que la injusticia",
  "Más vueltas que perro para echarse",
  "Menos calle que Venecia",
  "Menos carne que empanada de verdura",
  "Menos carne que pantorilla de tero",
  "Menos carne que rodilla de mosquito",
  "Menos carne que viernes santo",
  "Menos disimulado que ladrón de maracas con Parkinson",
  "Menos higiene que cepillo de inodoro",
  "Menos onda que bandera de chapa",
  "Menos onda que pelo lacio",
  "Menos patada que una pila",
  "Menos profundo que Pelopincho",
  "Ordinario como helado de panceta",
  "Pega como padrastro borracho",
  "Perdido como turco en la neblina",
  "Pesado como barrilete de mármol",
  "Pesado como collar de garrafas",
  "Pesado como collar de sandías",
  "Pesado como submarino a remo",
  "Pesado como topadora a pedal",
  "Pesado como vaca en regazo",
  "Petizo como esquimal de freezer",
  "Petizo como Tarzán de maceta",
  "Quilombero como Gilera de villero",
  "Seco como culo de perro",
  "Seco como lengua de loro",
  "Seco como toallita de traba",
  "Serio como perro en bote",
  "Sube como pedo de buzo",
  "Sutil como canapé de mondongo",
  "Te pasé como alambre caído",
  "Tenso como perro en bote",
  "Tenso como rengo en tiroteo",
  "Transpirado como salamín en guantera",
  "Transpirado como tapa de olla",
  "Transpirando como monja con atraso",
  "Va al frente como reja negra",
  "Va y viene como perro atado con goma",
]